## Vector arithmetic

In [2]:
import numpy as np

In [3]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

In [5]:
a+b

array([30, 60, 90])

In [6]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
a-b

array([10, 20, 30])

In [8]:
a-c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [9]:
multi=a*b
print(multi)

[ 200  800 1800]


In [10]:
div=a/b
print(div)

[2. 2. 2.]


In [11]:
scalar=5

In [12]:
list_a=[10,11, 12, 13, 14, 15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [13]:
list_as_array=np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [14]:
scalar*list_a

[10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15]

In [15]:
scalar*list_as_array

array([50, 55, 60, 65, 70, 75])